repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: c9d5fe3776c92519e0b7eb9175fb56400f2a518f
    hooks:
      - id: fmt
      - id: clippy
        name: clippy
        description: Lint rust sources
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
