version: "3.4"
services:
  app:
    image: ncrmro/planet-express
    build:
      context: .
      target: watcher
    command: cargo watch -x run
    volumes:
      - .:/app/
  db:
    image: postgres:10.12
    environment:
      POSTGRES_DB: pexp
      POSTGRES_USER: pexp
      POSTGRES_PASSWORD: pexp
    volumes:
      - .pgdata/:/var/lib/postgresql/data
    ports:
      - 5432:5432
