version: "3.4"
x-app: &app-template
    image: ncrmro/rust:watcher
    build:
      context: .
      target: watcher
    tty: true
    env_file:
      - .env
    environment:
      TERM: xterm-256color
      DATABASE_URL: postgres://pexp:pexp@db:5432/pexp
    depends_on:
      - db
    volumes:
      - .:/app/
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target

services:
  app:
    <<: *app-template
    volumes:
      - .:/app/
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    ports:
      - 8000:8000
  app-test:
    <<: *app-template
    command: cargo watch --watch src --watch tests --exec 'test -- --nocapture'
  app-migrations:
    <<: *app-template
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; sqlx mig run'
    volumes:
      - ./migrations/:/app/migrations/:rw
  db:
    image: postgres:10.12
    environment:
      POSTGRES_DB: pexp
      POSTGRES_USER: pexp
      POSTGRES_PASSWORD: pexp
    volumes:
      - pgdata/:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
  cargo-cache:
  target-cache:
