name: Docker Compose Actions Workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker complains if .env not present
        run: touch .env
      - name: Pull images
        run: docker-compose pull
      - name: Bring up the database
        run: docker-compose up -d db
      - name: Run migrations
        run:  docker-compose up app-migrations
      - name: Test
        run: docker-compose run app cargo test

# Build first layers..
# Some how share target cache?.
