name: Docker Compose Actions Workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker complains if .env not present
        run: touch .env
      - name: Build the stack
        run: docker-compose up -d db app-migrations
      - name: Test
        run: docker-compose run app cargo test

# Build first layers..
# Some how share target cache?.
