name: Docker Compose Actions Workflow
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - '*'
  pull:
    # Sequence of patterns matched against refs/heads
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker exec app cargo test

# Build first layers..
# Some how share target cache?.
