name: Docker Compose Actions Workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Docker complains if .env not present
        run: touch .env
      - name: Pull images
        run: docker-compose pull
      - name: Bring up the database
        run: docker-compose up -d db
      - name: Run migrations
        run:  docker-compose up app-migrations
      - name: Test
        run: docker-compose run app cargo test
      - name: LS LA
        run: ls -la target
      - name: LS LA
        run: ls -la target/.cache
      - name: LS LA
        run: ls -la target/.cache/cargo
#      - name: Compile final binary
#        run: docker-compose run app cargo build --release
#      - name: Build final release
#        run: docker build --tag registry.heroku.com/planetexpres/web .

